# Generated by Django 4.1.5 on 2023-04-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websites',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='website_url',
        ),
        migrations.DeleteModel(
            name='ScanResults',
        ),
    ]
