# Generated by Django 4.1.5 on 2023-04-28 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_websites_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('subdomain_id', models.AutoField(primary_key=True, serialize=False)),
                ('subdomain_name', models.CharField(max_length=100)),
                ('tech_stack', models.JSONField()),
                ('ip_address', models.CharField(max_length=50)),
                ('open_ports', models.TextField()),
                ('directories', models.JSONField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.websites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
