# Generated by Django 4.1.5 on 2023-04-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_subdomain_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='directories',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='open_ports',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='tech_stack',
            field=models.JSONField(null=True),
        ),
    ]
