# Generated by Django 4.1.5 on 2023-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_alter_subdomain_directories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='endpoints',
            field=models.JSONField(null=True),
        ),
    ]
